# Generated by Django 3.0.7 on 2020-06-21 09:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StateRegion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('trading_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('site_features', models.CharField(max_length=500)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fuelwatch.Brand')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fuelwatch.Region')),
                ('state_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fuelwatch.StateRegion')),
                ('suburb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fuelwatch.Suburb')),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelwatch.FuelStation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelwatch.Product')),
            ],
        ),
    ]
