# Generated by Django 3.0.3 on 2020-02-26 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('trading_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField()),
                ('fuel_type', models.IntegerField()),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelwatch.FuelStation')),
            ],
        ),
    ]
